### ISSUE TITLE
docs: Documentation improvement

### ISSUE THREAD

**Issue by On0n0k1** [zerodaycode/canyon-book#2]
The documentation is great. It discusses the important topics without dragging the subject. But I noticed there are several typos and some grammatical errors. Probably due to being written in a hurry.

May I make a pull request with some corrections? You can decide on the changes as you see fit.

If that is the case. Should I make pull request for each page? Or divide the changes between each paragraph?

**Comment by TheRustifyer** [comment]
@On0n0k1 I already tried to notify you via the PR that you opened. I would really like to see those changes and corrections. Are you still in the mood to make them?

If you go ahead:

> If that is the case. Should I make pull request for each page? Or divide the changes between each paragraph?

I think that a PR for each page is enought. As far as I see, the initial ones that you proposed are fine, so we could try like this at first

**Comment by On0n0k1** [comment]
Hello @Pyzyryab . Sure. I will start making those updates soon. Thanks. I thought you didn't like the changes I've made.
